import {
  FaTachometerAlt,
  FaUsers,
  FaStore,
  FaTicketAlt,
  FaCalendarAlt,
  FaTrophy,
  FaCreditCard,
  FaWallet,
  FaUserShield,
  FaCog,
} from "react-icons/fa";

export const SIDEBAR_ITEMS = [
  {
    key: "dashboard",
    label: "Dashboard",
    path: "/dashboard",
    icon: FaTachometerAlt,
    iconColor: "#2563eb", 
  },
  {
    key: "users",
    label: "Users",
    path: "/users",
    icon: FaUsers,
    iconColor: "#16a34a", 
  },
  {
    key: "retailers",
    label: "Retailers",
    path: "/retailers",
    icon: FaStore,
    iconColor: "#9333ea", 
  },
  {
    key: "tickets",
    label: "Tickets",
    path: "/tickets",
    icon: FaTicketAlt,
    iconColor: "#dc2626", 
  },
  {
    key: "draws",
    label: "Draws",
    path: "/draws",
    icon: FaCalendarAlt,
    iconColor: "#0ea5e9", 
  },
  {
    key: "results",
    label: "Results",
    path: "/results",
    icon: FaTrophy,
    iconColor: "#f59e0b", 
  },
  {
    key: "subscriptions",
    label: "Subscriptions",
    path: "/subscriptions",
    icon: FaCreditCard,
    iconColor: "#14b8a6", 
  },
  {
    key: "wallet",
    label: "Wallet",
    path: "/wallet",
    icon: FaWallet,
    iconColor: "#22c55e", 
  },
  {
    key: "permissions",
    label: "Permissions",
    path: "/permissions",
    icon: FaUserShield,
    iconColor: "#6366f1", 
  },
  {
    key: "settings",
    label: "Settings",
    path: "/settings",
    icon: FaCog,
    iconColor: "#64748b", 
  },
];
